DROP TABLE IF EXISTS line;
DROP TABLE IF EXISTS uploadrequest;

CREATE TABLE uploadrequest (
  id INT AUTO_INCREMENT PRIMARY KEY
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE line (
  id INT AUTO_INCREMENT PRIMARY KEY,
  value_of_line VARCHAR(256) NOT NULL,
  counter INT NOT NULL,
  request_id INT NOT NULL REFERENCES uploadrequest(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
